### ISSUE TITLE
Roadmap 1.3

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon.net#219]
# Version 1.3 - Release date 30.11.2021

This will include original game data updates 1.12 English and 1.11 German.

There might be more changes as well that will be added later.

## Remake fixes and improvements
- [x] #224 
- [x] #223 
- [x] #222 
- [x] Update LP when using healing potions etc #216
- [x] Allow skipping/closing popups and automap with space key #217
- [x] Allow confirming version in version selector with return key (and maybe also space key) #218
- [x] #225
- [x] #226 
- [x] #227 
- [x] #230 
- [x] #213 
- [x] #232 

## Original game data changes

- [x] Fix automap walls in beast cave and hill caves #199 (is this a remake bug?)
- [x] Fix Sandra quest (german only) to receive the chest key if you say "TOCHTER" instead of "SABINE"
- [x] Replace "ENKEL" by "ENKELKIND" in testament text
- [x] Replace "FISHERMEN" by "FISHERMAN" for NPC Sally
- [x] Spider in bandits' cellar now can move

**Comment by Pyrdacor** [comment]
## Features

- Added quicksave with Ctrl+1 to Ctrl+0 (slots 1-10)
- Added screenshot function (PrintScreen key or Ctrl+P)
- Added alternating animations for some 2D characters
- Options can now be scrolled with mouse wheel
- Automap can now be closed by keys Space and Esc
- You can now open the inventory with F1-F6 from automap
- Game version can now also be confirmed with keys Space or Return
- Other popups that can be closed by a click, can now also be closed with keys Space, Return or Esc
- Added noclip cheat
- Godmode now makes you immune to ailments


## Fixes

- Fixed that NPCs are sometimes drawn partly above the player
- When the last member is unable to select in fight, the game over screen is now shown
- Fixed raft dealer picture
- Places without 'closed' text index will now still block the player
- If a curse leads to negative values, there is no longer a negative overflow
- Items that are destroyed after use (e.g. torches) can not break anymore
- You can now use the numpad keys to enter numbers
- 2D movespeed now depends on the "travel graphics" map flag and not the world surface flag
- While using a horse, raft, ship, lizard or sand ship you can now still teleport if the
  target map allows travel types as well (e.g. teleport at the vortex or wind gates on a horse)
- Fixed baseline (rendering) while swimming
- Give gold/food buttons are now correctly enabled when your gold/food amount changes
- Fixed issue when you gave an item twice to an NPC
- Light will not be active in a dungeon when you sleep for hours just before the light source runs out
- Music is now correctly remembered through event chains
- LP/SP is now updated in the character info when using potions
- Fixed cursed items
- The item details will no longer show the "cursed" state if the item is not cursed anymore
- Using items in 3D now requires you to stand more closely to the tile with the event
- When falling down a hole or climbing down a ladder you are now placed at the correct position
- Removing events which have some visual on the automap, will now remove that visual (e.g. a pile)
- Levitating/climbing now only works if the event is still active
- Levitating/climbing/falling will now place you on the correct position in all cases
-
